### ISSUE TITLE
A syntax error occurred when executing npm start

### ISSUE THREAD

**Issue by wugx** [zuiidea/antd-admin#1105]
```
[root@antd-admin]# npm run start

> antd-admin@5.3.0 start /wuguoxiao/antd-admin
> umi dev

/wuguoxiao/antd-admin/node_modules/@umijs/deps/compiled/chalk/index.js:1
(function (exports, require, module, __filename, __dirname) { module.exports=(()=>{var e={68:(e,t,n)=>{"use strict";e=n.nmd(e);const r=(e,t)=>(...n)=>{const r=e(...n);return`r+t}m`};const o=(e,t)=>(...n)=>{const r=e(...n);return`38+t};5;${r}m`};const s=(e,t)=>(...n)=>{const r=e(...n);return`38+t};2;${r[0]};${r[1]};${r[2]}m`};const l=e=>e;const c=(e,t,n)=>[e,t,n];const i=(e,t,n)=>{Object.defineProperty(e,t,{get:()=>{const r=n();Object.defineProperty(e,t,{value:r,enumerable:true,configurable:true});return r},enumerable:true,configurable:true})};let a;const u=(e,t,r,o)=>{if(a===undefined){a=n(53)}const s=o?10:0;const l={};for(const[n,o]of Object.entries(a)){const c=n==="ansi16"?"ansi":n;if(n===t){l[c]=e(r,s)}else if(typeof o==="object"){l[c]=e(o[t],s)}}return l};function assembleStyles(){const e=new Map;const t={modifier:{reset:[0,0],bold:[1,22],dim:[2,22],italic:[3,23],underline:[4,24],inverse:[7,27],hidden:[8,28],strikethrou

SyntaxError: Unexpected token *
    at NativeCompileCache._moduleCompile (/wuguoxiao/antd-admin/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/wuguoxiao/antd-admin/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/wuguoxiao/antd-admin/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at _chalk (/wuguoxiao/antd-admin/node_modules/@umijs/utils/lib/index.js:280:39)
    at Object.get [as chalk] (/wuguoxiao/antd-admin/node_modules/@umijs/utils/lib/index.js:56:12)

npm ERR! Linux 4.18.0-193.el8.jd_001.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! antd-admin@5.3.0 start: `umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd-admin@5.3.0 start script 'umi dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the antd-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     umi dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs antd-admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls antd-admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /wuguoxiao/antd-admin/npm-debug.log
```

```
[root@ntd-admin]# cat /wuguoxiao/antd-admin/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.17.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle antd-admin@5.3.0~prestart: antd-admin@5.3.0
6 silly lifecycle antd-admin@5.3.0~prestart: no script for prestart, continuing
7 info lifecycle antd-admin@5.3.0~start: antd-admin@5.3.0
8 verbose lifecycle antd-admin@5.3.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle antd-admin@5.3.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/wuguoxiao/antd-admin/node_modules/.bin:/export/servers/git-1.9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/export/servers/apache-maven-3.5.4/bin:/export/servers/sdk/platform-tools:/export/servers/sdk/tools:/export/servers/sdk/build-tools/25.0.3
10 verbose lifecycle antd-admin@5.3.0~start: CWD: /wuguoxiao/antd-admin
11 silly lifecycle antd-admin@5.3.0~start: Args: [ '-c', 'umi dev' ]
12 silly lifecycle antd-admin@5.3.0~start: Returned: code: 1  signal: null
13 info lifecycle antd-admin@5.3.0~start: Failed to exec start script
14 verbose stack Error: antd-admin@5.3.0 start: `umi dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid antd-admin@5.3.0
16 verbose cwd /wuguoxiao/antd-admin
17 error Linux 4.18.0-193.el8.jd_001.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
19 error node v6.17.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error antd-admin@5.3.0 start: `umi dev`
22 error Exit status 1
23 error Failed at the antd-admin@5.3.0 start script 'umi dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the antd-admin package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     umi dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs antd-admin
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls antd-admin
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by superlbr** [comment]
use yarn or cnpm
