### ISSUE TITLE
npm start 报错  Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by albafica2015** [zuiidea/antd-admin#148]
ERROR in ./src/index.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/Ling"
    at /Users/Ling/antd-admin-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/Ling/antd-admin-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/Ling/antd-admin-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/Ling/antd-admin-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/Ling/antd-admin-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/Ling/antd-admin-webpack/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/Ling/antd-admin-webpack/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/Ling/antd-admin-webpack/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/Ling/antd-admin-webpack/node_modules/babel-loader/lib/index.js:38:20)
 @ multi index

**Comment by wuyongdec** [comment]
cnpm install xx，现在dev版本，不知道是不是package.json还没有来得及加
