### ISSUE TITLE
运行'npm run dev'出现“user.less Module build failed”

### ISSUE THREAD

**Issue by justinxguo** [zuiidea/antd-admin#162]
把master最新代码clone到本地后，运行‘npm run dev’，就会出现如下异常：
`ERROR in ./src/routes/dashboard/components/user.less
Module build failed: Error: Loader D:\gitlab\antd-admin\node_modules\atool-build\node_modules\url\url.js?limit=10000 didn't return a function
    at DependenciesBlock.loadPitch (D:\gitlab\antd-admin\node_modules\webpack-core\lib\NormalModuleMixin.js:215:20)
    at DependenciesBlock.doBuild (D:\gitlab\antd-admin\node_modules\webpack-core\lib\NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (D:\gitlab\antd-admin\node_modules\atool-build\node_modules\webpack\lib\NormalModule.js:84:14)
    at Compilation.buildModule (D:\gitlab\antd-admin\node_modules\atool-build\node_modules\webpack\lib\Compilation.js:126:9)
    at D:\gitlab\antd-admin\node_modules\atool-build\node_modules\webpack\lib\Compilation.js:309:10
    at D:\gitlab\antd-admin\node_modules\atool-build\node_modules\webpack\lib\NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (D:\gitlab\antd-admin\node_modules\tapable\lib\Tapable.js:75:69)
    at onDoneResolving (D:\gitlab\antd-admin\node_modules\atool-build\node_modules\webpack\lib\NormalModuleFactory.js:38:11)
    at onDoneResolving (D:\gitlab\antd-admin\node_modules\atool-build\node_modules\webpack\lib\NormalModuleFactory.js:121:6)
    at D:\gitlab\antd-admin\node_modules\atool-build\node_modules\webpack\lib\NormalModuleFactory.js:116:7
 @ ./src/routes/dashboard/components/user.js 21:12-34
`

**Comment by zuiidea** [comment]
please reinstall `npm i` or  `cnpm i`

**Comment by justinxguo** [comment]
把user.less中“background-image: ~ "url(./user-background.png)";”这一行注释掉就好了。

**Comment by zuiidea** [comment]
是不是`~`后面多了个空格，我windows，这边没问题的

**Comment by justinxguo** [comment]
还是不行，只能注释掉。`~`后面空格删了也一样不行。
