### ISSUE TITLE
修改roadhog加载以后pagejson没有引用包吧？

### ISSUE THREAD

**Issue by tigaly** [zuiidea/antd-admin#189]
如题

**Comment by zuiidea** [comment]
因为直接写在`pagejson`里，`npm install`安装后的版本不是最新的，所以为了不必要的麻烦，单独`npm i roadhog@0.6.0-beta.3 -g`

**Comment by tigaly** [comment]
哦，我用过以后登陆还是有问题呢，三个用户都验证不过去

**Comment by zuiidea** [comment]
其实就是`roadhog`的版本不对，接口拿不到参数，这样试试呢

-  保证package.json里没有roadhog
-  删除`node_modules`
- `npm i`
- `npm i roadhog@0.6.0-beta.3 -g`

**Comment by tigaly** [comment]
我已经做过这个操作了，而且我还重新下了一份代码实验了下还是不行，而且找不到错误原因或者错误提示

**Comment by zuiidea** [comment]
- 看看控制台和cmd里有没有报什么错误呢
- `roadhog -v`确认一下版本呢

**Comment by tigaly** [comment]
roadhog -v 是 0.6.0-beta.3，cmd没有任何报错
另外，我改了下代码跳过认证以后，用那个request模块实验，rest接口调用返回结果没有任何问题

**Comment by zuiidea** [comment]
你看的哪一个分支呢

**Comment by tigaly** [comment]
master

**Comment by zuiidea** [comment]
![gif](https://cloud.githubusercontent.com/assets/16070518/25111784/a242ad64-241f-11e7-988d-dd254c431f73.gif)

刚刚试了下，最新的代码应该是没什么问题的🙃

**Comment by tigaly** [comment]
你这个是什么浏览器？我是用Safari 10.1和chrome 57.0 测试的不行
```
请求中
url:http://localhost:8000/api/v1/userInfo
method:
params:null
请求完成
{"success":true,"message":"Not Login","status":200}
```
```
请求中
url:http://localhost:8000/api/v1/user/login
method:post
params:{"username":"admin","password":"admin6"}
请求完成
{"success":false,"status":500,"message":"Internal Server Error"}
```

这个是用request请求的结果

**Comment by zuiidea** [comment]
我用的chrome，但是肯定跟浏览器没有关系的
是`src/mock/user.js`的问题，或者说是`roadhog`的问题
你在
```
[`POST ${apiPrefix}/user/login`] (req, res) {
...
console.log(req.body)
...
}
```
- 首先看下`req.body`有值没
- 另外看下这个函数其他句子有错没

**Comment by tigaly** [comment]
```
CHANGED ./src/mock/users.js
req is undefined
TypeError: Cannot read property 'username' of undefined
    at undefined (/Users/tigaly/react/antd-admin/src/mock/users.js:63:27)
    at mockHandler (/Users/tigaly/react/antd-admin/node_modules/roadhog/lib/utils/mock.js:74:13)
    at Layer.handle [as handle_request] (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/layer.js:95:5)
    at /Users/tigaly/react/antd-admin/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/index.js:275:10)
    at goNext (/Users/tigaly/react/antd-admin/node_modules/webpack-dev-middleware/middleware.js:28:49)
    at webpackDevMiddleware (/Users/tigaly/react/antd-admin/node_modules/webpack-dev-middleware/middleware.js:36:11)
    at Layer.handle [as handle_request] (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/index.js:317:13)
    at /Users/tigaly/react/antd-admin/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/index.js:275:10)
```

看错误确实是有问题，但是这个没法解释另外一个 [`POST ${apiPrefix}/users`](req, res)，这个就没有问题，请求结果都是正常，也没有报错

**Comment by zuiidea** [comment]
因为`users`是用的`req.query`，
我严重怀疑你的`node_modules`已经腐败了，
你看看`node_modules`文件夹下面有没有`roadhog`相关文件夹

**Comment by tigaly** [comment]
问题是这个操作我已经做了好多次了。。。
```
请求中
url:http://localhost:8000/api/v1/userInfo
method:
params:null
请求完成
{"success":true,"message":"Not Login","status":200}
```
问题是我就算用别的方式post成功登陆，也会从这个userinfo里面验证的是Not Login

**Comment by zuiidea** [comment]
![image](https://cloud.githubusercontent.com/assets/16070518/25112972/1fceb244-2427-11e7-951c-aec5a895f43b.png)

看看`antd-admin/node_modules/roadhog/packge.json`的`version`是不是`0.6.0-beta.3`

**Comment by tigaly** [comment]
上面那个问题确实是我误操作，我改了版本就可以了，但是登陆依然有问题
```
effects: {
    * queryUser({
      payload,
    }, { call, put }) {
      const data = yield call(getUserInfo, parse(payload));

      if (data.success && data.user) {
        console.log('result s is ' + data.success + ' ' + data.user);
        yield put({
          type: 'queryUserSuccess',
          payload: data.user,
        });
        if (location.pathname === '/login') {
          yield put(routerRedux.push('/dashboard'));
        }
      } else {
        console.log('result is ' + data.success + ' ' + data.user);
        if (location.pathname !== '/login') {
          let from = location.pathname
          if (location.pathname === '/dashboard') {
            from = '/dashboard'
          }
          window.location = `${location.origin}/login?from=${from}`
        }
      }
    },
```

这段我发现在登陆的时候就不会走到这个if里，两个console没有一个会打印的

**Comment by zuiidea** [comment]
你可以在if外面打印data 看看呢

**Comment by tigaly** [comment]
一样，我试过，我就是在外面打印不了才写到里面的

**Comment by zuiidea** [comment]
🙃我有点不服，你把有问题的代码推到https://github.com/tigaly/antd-admin，我看看呢

**Comment by tigaly** [comment]
哈，好的，我提交了，commit名字是 测试登陆
顺带，我发现问题可能出在utils/request这里
```
return fetch(options).then((response) => {
    const { statusText, status } = response;
    const data = options.fetchType === 'YQL' ? response.data.query.results.json : response.data;
    console.log('service is ' + JSON.stringify(data));
    return {
      success: true,
      message: statusText,
      status,
      ...data,
    };
```
这里的输出是
```
service is {"message":"Not Login"}
```

**Comment by zuiidea** [comment]
![image](https://cloud.githubusercontent.com/assets/16070518/25113855/e598e8f0-242c-11e7-8c8f-d4c199435035.png)
你的代码没有问题的🙃

**Comment by tigaly** [comment]
哈，我登陆的时候就一直不行，一直是  {"message":"Not Login"} 的提示，这是为什么呢？

**Comment by zuiidea** [comment]
登录的`req.body`你能看到吗

**Comment by tigaly** [comment]
req is {"username":"admin","password":"admin"}

**Comment by zuiidea** [comment]
看下cookie里有没有token呢

**Comment by tigaly** [comment]
```
return fetch(options).then((response) => {
    const { statusText, status } = response;
    console.log('options is ' + JSON.stringify(options));
    console.log('response is ' + JSON.stringify(response));
    const data = options.fetchType === 'YQL' ? response.data.query.results.json : response.data;
    console.log('service is ' + JSON.stringify(data));
    return {
      success: true,
      message: statusText,
      status,
      ...data,
    };
```
浏览器这边的日志：
```
options is {"url":"/userInfo","method":"get","data":{}}
response is {"data":{"message":"Not Login"},"status":200,"statusText":"OK","headers":{"date":"Tue, 18 Apr 2017 04:01:58 GMT","etag":"W/\"17-+bfjK/HPiNFQO8lahRt7of+M3Yc\"","x-powered-by":"Express","content-length":"23","vary":"Accept-Encoding","content-type":"application/json; charset=utf-8"},"config":{"transformRequest":{},"transformResponse":{},"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"headers":{"Accept":"application/json, text/plain, */*"},"baseURL":"http://localhost:8000/api/v1","method":"get","url":"http://localhost:8000/api/v1/userInfo"},"request":{}}
service is {"message":"Not Login"}
result is {"success":true,"message":"Not Login","status":200} 
```
后台的日志，这应该是mock返回的：
```
req is {"username":"admin","password":"admin"}
```

**Comment by tigaly** [comment]
cookie里有token，内容是
```
%7B%22id%22%3A1%2C%22deadline%22%3A1492574701839%7D
```

**Comment by zuiidea** [comment]
调试这个`[`GET ${apiPrefix}/userInfo`] (req, res) {}`

**Comment by tigaly** [comment]
```
➜  ~ curl http://localhost:8000/api/v1/user/login -d "username=admin&password=admin"
{"success":true,"message":"Ok"}%                                                
➜  ~ curl http://localhost:8000/api/v1/userInfo
{"message":"Not Login"}%
```

看来问题已经定位的很准确了，为什么会这样呢？先去吃饭，下午再来看看，谢谢大佬陪我在这调试问题

**Comment by zuiidea** [comment]
就是这句的问题了啊
`const cookies = qs.parse(req.headers.cookie, { delimiter: ';' })`
看看是req.headers.cookie这个没有，还是qs.parse没解析对

**Comment by tigaly** [comment]
大佬你说的那句输出是这样的，token不知道为啥完全没拿到呢？
```
req is {"username":"guest","password":"guest"}
cookies is {"__utma":"111872281.1775425276.1491183587.1491183587.1491183587.1"," __utmz":"111872281.1491183587.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)"," token":"{\"id\":1,\"deadline\":1492579744262}"}
cookies is {"__utma":"111872281.1775425276.1491183587.1491183587.1491183587.1"," __utmz":"111872281.1491183587.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)"," token":"{\"id\":1,\"deadline\":1492579744262}"}
```

**Comment by tigaly** [comment]
问题是qs解析的问题，大佬你能把你qs解析的结果贴出来么？我这边qs解析以后，token前面有个空格，导致的这个问题

**Comment by sbyps** [comment]
我也出现了这样的问题，debug了好久，直接是cnpm i roadhog，版本是0.5.3，so sad，作者你看能不能在readme中注明一下这个坑

**Comment by tigaly** [comment]
@zuiidea 
这个问题已经解决了，就是qs转换的问题，代码改成这样，去除所有的多余空格就好
```
const cookies = qs.parse(req.headers.cookie.replace(/\s/g, ""), { delimiter: ';' });
```

PS：这个问题可能在windows上没有，在osx和linux上可能有，至少我的osx上有，大佬有空可以测试验证下

**Comment by sbyps** [comment]
@tigaly centos上不存在这个问题，osx没有=。=

**Comment by tigaly** [comment]
@sbyps 哈，难道只有osx上有这个bug？或者难道只有我有这个bug？（天选之人2333）

**Comment by zuiidea** [comment]
@sbyps 好吧，我提醒明显一点

**Comment by xyunsh** [comment]
mac 同样的问题

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/pull/202/commits/7284cad8aa982e941e281dcf60c87abbeba2d4de
