### ISSUE TITLE
4.14 版本  npm run build 报错，怎么解决？

### ISSUE THREAD

**Issue by albafica2015** [zuiidea/antd-admin#218]
lingtongdeiMac:antd-admin-master Ling$ npm run build

> @ build /Users/Ling/antd-admin-master
> roadhog build --analyze

Creating an optimized production build...
Failed to compile.

Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/Ling/antd-admin-master"
    at /usr/local/lib/node_modules/roadhog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/local/lib/node_modules/roadhog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/roadhog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/roadhog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/usr/local/lib/node_modules/roadhog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/roadhog/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/roadhog/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/roadhog/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/usr/local/lib/node_modules/roadhog/node_modules/babel-loader/lib/index.js:46:20)
    at /usr/local/lib/node_modules/roadhog/node_modules/babel-loader/lib/fs-cache.js:79:18
    at ReadFileContext.callback (/usr/local/lib/node_modules/roadhog/node_modules/babel-loader/lib/fs-cache.js:15:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ build: `roadhog build --analyze`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script 'roadhog build --analyze'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     roadhog build --analyze
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Ling/antd-admin-master/npm-debug.log
lingtongdeiMac:antd-admin-master Ling$

**Comment by blackboyhc** [comment]
我也有相同問題，請問怎麼解決？

**Comment by superlbr** [comment]
1. 更新版本
2. 使用yarn install安装依赖
