### ISSUE TITLE
刚git了项目，运行npm run dev就报错了

### ISSUE THREAD

**Issue by EricHan0723** [zuiidea/antd-admin#259]
> @ dev D:\demo
> roadhog server

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8000
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

请问是什么原因呢？

**Comment by zuiidea** [comment]
你的8000端口是不是被占用了
