### ISSUE TITLE
npm run build:dll在mac os x下编译失败

### ISSUE THREAD

**Issue by phproot** [zuiidea/antd-admin#451]
```
Module not found: Error: Cannot resolve module 'fs' ……
Module not found: Error: Cannot resolve module 'tls' ……
Module not found: Error: Cannot resolve module 'net' ……
Module not found: Error: Cannot resolve module 'dns' ……

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! antd-admin@4.3.0 build:dll: `roadhog buildDll`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd-admin@4.3.0 build:dll script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/code/.npm/_logs/2017-07-30T14_36_10_481Z-debug.log

```

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/pull/452/commits/0f27528d2f50c3d00ed8eb51252e2ecf36f04d2f

retry?

**Comment by phproot** [comment]
@zuiidea 还是无法进行编译，错误依旧。

**Comment by phproot** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:dll' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'prebuild:dll', 'build:dll', 'postbuild:dll' ]
5 info lifecycle antd-admin@4.3.0~prebuild:dll: antd-admin@4.3.0
6 info lifecycle antd-admin@4.3.0~build:dll: antd-admin@4.3.0
7 verbose lifecycle antd-admin@4.3.0~build:dll: unsafe-perm in lifecycle true
8 verbose lifecycle antd-admin@4.3.0~build:dll: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/code/Desktop/app/antd-admin/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/code/go/bin
9 verbose lifecycle antd-admin@4.3.0~build:dll: CWD: /Users/code/Desktop/app/antd-admin
10 silly lifecycle antd-admin@4.3.0~build:dll: Args: [ '-c', 'roadhog buildDll' ]
11 silly lifecycle antd-admin@4.3.0~build:dll: Returned: code: 1  signal: null
12 info lifecycle antd-admin@4.3.0~build:dll: Failed to exec build:dll script
13 verbose stack Error: antd-admin@4.3.0 build:dll: `roadhog buildDll`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid antd-admin@4.3.0
15 verbose cwd /Users/code/Desktop/app/antd-admin
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/8.2.1/bin/node" "/usr/local/bin/npm" "run" "build:dll"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error antd-admin@4.3.0 build:dll: `roadhog buildDll`
22 error Exit status 1
23 error Failed at the antd-admin@4.3.0 build:dll script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by phproot** [comment]
重新克隆后得到的错误……依然无法编译。

```
Creating dll bundle...
Failed to compile.

  TypeError: Cannot read property '0' of undefined

  - ExternalModuleFactoryPlugin.js:19
    [ant-admin]/[webpack]/lib/ExternalModuleFactoryPlugin.js:19:40

  - NormalModuleFactory.js:159
    [lib]/[roadhog]/[webpack]/lib/NormalModuleFactory.js:159:3

  - Tapable.js:75 NormalModuleFactory.applyPluginsAsyncWaterfall
    [lib]/[roadhog]/[webpack]/[tapable]/lib/Tapable.js:75:69

  - NormalModuleFactory.js:144 NormalModuleFactory.create
    [lib]/[roadhog]/[webpack]/lib/NormalModuleFactory.js:144:8

  - Compilation.js:356 Compilation.process [as _addModuleChain]
    [lib]/[roadhog]/[webpack]/lib/Compilation.js:356:16

  - Compilation.js:424 Compilation.process [as addEntry]
    [lib]/[roadhog]/[webpack]/lib/Compilation.js:424:7

  - SingleEntryPlugin.js:24 Compiler.compiler.plugin
    [ant-admin]/[webpack]/lib/SingleEntryPlugin.js:24:16

  - Tapable.js:107 Compiler.applyPluginsParallel
    [lib]/[roadhog]/[webpack]/[tapable]/lib/Tapable.js:107:14

  - Compiler.js:394 Compiler.compile
    [lib]/[roadhog]/[webpack]/lib/Compiler.js:394:7

  - Compiler.js:203 Compiler.runAsChild
    [lib]/[roadhog]/[webpack]/lib/Compiler.js:203:7

  - compiler.js:70
    [ant-admin]/[html-webpack-plugin]/lib/compiler.js:70:19

  - debuggability.js:300 Promise._execute
    [ant-admin]/[html-webpack-plugin]/[bluebird]/js/release/debuggability.js:300:9

  - promise.js:483 Promise._resolveFromExecutor
    [ant-admin]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:483:18

  - promise.js:79 new Promise
    [ant-admin]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:79:10

  - compiler.js:69 Object.compileTemplate
    [ant-admin]/[html-webpack-plugin]/lib/compiler.js:69:10

  - index.js:47 Compiler.<anonymous>
    [ant-admin]/[html-webpack-plugin]/index.js:47:40

  - Tapable.js:107 Compiler.applyPluginsParallel
    [lib]/[roadhog]/[webpack]/[tapable]/lib/Tapable.js:107:14

  - Compiler.js:394 Compiler.compile
    [lib]/[roadhog]/[webpack]/lib/Compiler.js:394:7

  - Compiler.js:173 Compiler.<anonymous>
    [lib]/[roadhog]/[webpack]/lib/Compiler.js:173:9

  - Compiler.js:302 Compiler.readRecords
    [lib]/[roadhog]/[webpack]/lib/Compiler.js:302:10

  - Compiler.js:170 Compiler.<anonymous>
    [lib]/[roadhog]/[webpack]/lib/Compiler.js:170:8

  - Tapable.js:67 Compiler.next
    [lib]/[roadhog]/[webpack]/[tapable]/lib/Tapable.js:67:11


```

**Comment by zuiidea** [comment]
刚刚又测试了一下，我这里没什么问题
- `roadhog -v`看一下是不是1.0.0-beta.7版本
- 这种情况感觉有点像安装出错了，不要将roadhog安装到全局，安装到本项目试试

![image](https://user-images.githubusercontent.com/16070518/28760140-e4bbf610-75d6-11e7-80a8-e07cb7cc5d88.png)

**Comment by phproot** [comment]
en,因为我的roadhog安装到了全局，且没有更新到最新版本。所以导致编译失败。

**Comment by zuiidea** [comment]
```
Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
```
对的，还有这个错，roadhog里有webpack

http://blog.csdn.net/u013240543/article/details/51792261

**Comment by phproot** [comment]
是的，我的webpack也很悲催的安装到了全局，因为当时编译不通的时候想尝试一下把webpack安装到全局，结果依然不通。嘿嘿。文档中改进一下，提醒一下兄弟们不要把webpack和roadhog安装到全局去？
