### ISSUE TITLE
启动都启动不了报错

### ISSUE THREAD

**Issue by albafica2015** [zuiidea/antd-admin#676]
[babel-plugin-dva-hmr][INFO] got routerPath ./router
crypto.js:74
  this._handle.update(data, encoding);

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at DelegatedModule.updateHash (/Users/Ling/zhaogang/antd-admin/node_modules/._webpack@3.8.1@webpack/lib/DelegatedModule.js:93:8)
    at _modules.forEach.m (/Users/Ling/zhaogang/antd-admin/node_modules/._webpack@3.8.1@webpack/lib/Chunk.js:356:32)
    at SortableSet.forEach (native)
    at Chunk.updateHash (/Users/Ling/zhaogang/antd-admin/node_modules/._webpack@3.8.1@webpack/lib/Chunk.js:356:17)
    at Compilation.createHash (/Users/Ling/zhaogang/antd-admin/node_modules/._webpack@3.8.1@webpack/lib/Compilation.js:1334:10)
    at sealPart2 (/Users/Ling/zhaogang/antd-admin/node_modules/._webpack@3.8.1@webpack/lib/Compilation.js:645:9)
    at Compilation.applyPluginsAsyncSeries (/Users/Ling/zhaogang/antd-admin/node_modules/._tapable@0.2.8@tapable/lib/Tapable.js:195:46)
    at Compilation.seal (/Users/Ling/zhaogang/antd-admin/node_modules/._webpack@3.8.1@webpack/lib/Compilation.js:605:8)
    at applyPluginsParallel.err (/Users/Ling/zhaogang/antd-admin/node_modules/._webpack@3.8.1@webpack/lib/Compiler.js:508:17)

**Comment by albafica2015** [comment]
怎么回事啊？ 有人知道吗？

**Comment by allinshang** [comment]
运行什么报这个错误的？

**Comment by allinshang** [comment]
看着是改了什么东西呢

**Comment by superlbr** [comment]
Data must be a string or a buffer。。。请检查代码
