### ISSUE TITLE
npm run build:dll 失败

### ISSUE THREAD

**Issue by zjtws** [zuiidea/antd-admin#694]
麻烦各位大神看一下是什么原因，谢谢
> antd-admin@4.3.7 build:dll /Users/taoweisong/Projects/github/antd-admin
> roadhog buildDll

/Users/taoweisong/Projects/github/antd-admin/webpack.config.js:24
    webpackConfig.plugins.push(new webpack.LoaderOptionsPlugin({
                               ^

TypeError: webpack.LoaderOptionsPlugin is not a constructor
    at module.exports (/Users/taoweisong/Projects/github/antd-admin/webpack.config.js:21:7)
    at applyWebpackConfig (/Users/taoweisong/Projects/github/antd-admin/node_modules/.npminstall/roadhog/1.3.1/roadhog/lib/utils/applyWebpackConfig.js:32:29)
    at build (/Users/taoweisong/Projects/github/antd-admin/node_modules/.npminstall/roadhog/1.3.1/roadhog/lib/buildDll.js:85:45)
    at Object.<anonymous> (/Users/taoweisong/Projects/github/antd-admin/node_modules/.npminstall/roadhog/1.3.1/roadhog/lib/buildDll.js:218:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by Maple-Ro** [comment]
我也遇到过这个问题，我的解决方法如下：
1、npm uninstall -g webpack/roadhog
2、delete node_modules
3、npm i
注：如果能翻墙，就不要用cnpm

**Comment by superlbr** [comment]
yarn 也可以，npm国内目前还行
