### ISSUE TITLE
下载，安装就报错

### ISSUE THREAD

**Issue by KingHUBIYIN** [zuiidea/antd-admin#713]
17:26	Can't analyse webpack.config.js: coding assistance will ignore module resolution rules in this file.
		Possible reasons: this file is not a valid webpack configuration file or its format is not currently supported by the IDE

17:26	ESLint is enabled: 'eslint' is listed in package.json.
		Disable ESLint

17:26	Error on attempt to find parent and base ESLint configuration files of '.eslintrc': Cannot find module 'babel-eslint'
		Error: Cannot find module 'babel-eslint'
		at ModuleResolver.resolve (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\util\module-resolver.js:74:19)
		at loadFromDisk (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:500:42)
		at Object.load (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:550:20)
		at Config.loadSpecificConfig (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\config.js:139:46)
		at new Config (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\config.js:101:14)
		at new CLIEngine (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:420:23)
		at Object.execute (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\cli.js:163:28)
		at Object.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\bin\eslint.j... (show balloon)

**Comment by superlbr** [comment]
npm依赖有问题，建议删掉node_modules，用yarn或者cnpm重新装一下依赖
