### ISSUE TITLE
webpack 版本和roadhog版本请说明

### ISSUE THREAD

**Issue by xueyise** [zuiidea/antd-admin#762]
下载完后不能编译，网上说是webpack和roadhog 版本不对
运行的是4.3.6版本的antd-admin 
webpack 版本是4.1.1
roadhog版本是2.2.0
错误信息：

module.js:491
    throw err;
    ^

Error: Cannot find module 'webpack/lib/Chunk'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\doc\antd-admin-4.3.6\node_modules\extract-text-webpack-plugin\dist\index.js:17:14)
    at Module._compile (module.js:573:30)
    at Module._extensions..js (module.js:584:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\doc\antd-admin-4.3.6\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! antd-admin@4.3.6 build: `roadhog build`
npm ERR! Exit status 1

**Comment by superlbr** [comment]
1. antd-admin 最新的是4.3.9，直接clone或者下载，release不是新的
2. antd-admin 默认"roadhog": "1.3.1"
