### ISSUE TITLE
最新版本 npm run build失败

### ISSUE THREAD

**Issue by forgotwho** [zuiidea/antd-admin#923]
git clone https://github.com/zuiidea/antd-admin.git
npm install
npm run start 可以正常运行
但是npm run build就报错，无法生成 dist目录

以下是部分错误日志
traverse\lib\path\index.js:161:24)
    at Scope.crawl (D:\workspace_react\antd-admin-5.0\node_modules\@babel\traver
se\lib\scope\index.js:684:10)
    at PluginPass.Program (D:\workspace_react\antd-admin-5.0\node_modules\babel-
plugin-transform-react-remove-prop-types\lib\index.js:361:29)

 @ ./src/pages/.umi-production/router.js 335:15-337:31 354:15-356:31
 @ ./src/pages/.umi-production/umi.js
 @ multi ./src/pages/.umi-production/umi.js

 error  in ./src/pages/user/index.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: D:\workspace_react\antd-admin-5.0\src\pages\user\index.js: Duplicate
declaration "React"
> 1 | import React, { PureComponent } from 'react'
    |        ^
  2 | import PropTypes from 'prop-types'
  3 | import { router } from 'utils'
  4 | import { connect } from 'dva'
    at File.buildCodeFrameError (D:\workspace_react\antd-admin-5.0\node_modules\
@babel\core\lib\transformation\file\file.js:261:12)
    at Scope.checkBlockScopedCollisions (D:\workspace_react\antd-admin-5.0\node_
modules\@babel\traverse\lib\scope\index.js:347:22)
    at Scope.registerBinding (D:\workspace_react\antd-admin-5.0\node_modules\@ba

**Comment by forgotwho** [comment]
@ ./src/pages/.umi-production/router.js 59:15-61:22 70:15-72:22
 @ ./src/pages/.umi-production/umi.js
 @ multi ./src/pages/.umi-production/umi.js

 error  in ./src/pages/login/index.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /home/forte/antd-admin/src/pages/login/index.js: Duplicate declaration "React"
> 1 | import React, { PureComponent, Fragment } from 'react'
    |        ^
  2 | import PropTypes from 'prop-types'
  3 | import { connect } from 'dva'
  4 | import { Button, Row, Form, Icon, Input } from 'antd'

**Comment by forgotwho** [comment]
[test@localhost antd-admin]$ npm run build

> antd-admin@5.0.0 build /home/test/antd-admin
> umi build

[17:16:44] webpack compiled in 31s 437ms
 ERROR  Failed to compile with 14 errors                                                                                                                                                                                         17:16:44

 error  in ./src/components/Loader/Loader.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /home/test/antd-admin/src/components/Loader/Loader.js: Duplicate declaration "React"
> 1 | import React from 'react'
    |        ^
  2 | import PropTypes from 'prop-types'
  3 | import classNames from 'classnames'
  4 | import styles from './Loader.less'
    at File.buildCodeFrameError (/home/test/antd-admin/node_modules/@babel/core/lib/transformation/file/file.js:261:12)
    at Scope.checkBlockScopedCollisions (/home/test/antd-admin/node_modules/@babel/traverse/lib/scope/index.js:347:22)
    at Scope.registerBinding (/home/test/antd-admin/node_modules/@babel/traverse/lib/scope/index.js:504:16)
    at Scope.registerDeclaration (/home/test/antd-admin/node_modules/@babel/traverse/lib/scope/index.js:452:14)
    at Object.Declaration (/home/test/antd-admin/node_modules/@babel/traverse/lib/scope/index.js:125:12)
    at NodePath._call (/home/test/antd-admin/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/home/test/antd-admin/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/home/test/antd-admin/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/home/test/antd-admin/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/home/test/antd-admin/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/home/test/antd-admin/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/home/test/antd-admin/node_modules/@babel/traverse/lib/index.js:94:17)
    at traverse (/home/test/antd-admin/node_modules/@babel/traverse/lib/index.js:76:12)
    at NodePath.traverse (/home/test/antd-admin/node_modules/@babel/traverse/lib/path/index.js:161:24)
    at Scope.crawl (/home/test/antd-admin/node_modules/@babel/traverse/lib/scope/index.js:684:10)
    at PluginPass.Program (/home/test/antd-admin/node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js:361:29)

 @ ./src/pages/.umi-production/router.js 30:22-84 41:24-86 52:24-86 63:24-86 74:24-86 85:24-86 96:24-86 107:24-86 118:24-86 129:24-86 140:24-86 151:24-86 162:24-86 179:24-86 196:24-86 213:24-86 230:24-86 247:24-86 264:24-86 275:24-86 286:24-86 303:24-86 320:24-86 339:24-86 358:24-86 367:24-86
 @ ./src/pages/.umi-production/umi.js
 @ multi ./src/pages/.umi-production/umi.js

 error  in ./src/layouts/index.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /home/test/antd-admin/src/layouts/index.js: Duplicate declaration "React"
> 1 | import React, { Component } from 'react'
    |        ^
  2 | import withRouter from 'umi/withRouter'
  3 | import { LocaleProvider } from 'antd'
  4 | import { I18nProvider } from '@lingui/react'
    at File.buildCodeFrameError (/home/test/antd-admin/node_modules/@babel/core/lib/transformation/file/file.js:261:12)
    at Scope.checkBlockScopedCollisions (/home/test/antd-admin/node_modules/@babel/traverse/lib/scope/index.js:347:22)
    at Scope.registerBinding (/home/test/antd-admin/node_modules/@babel/traverse/lib/scope/index.js:504:16)
    at Scope.registerDeclaration (/home/test/antd-admin/node_modules/@babel/traverse/lib/scope/index.js:452:14)
    at Object.Declaration (/home/test/antd-admin/node_modules/@babel/traverse/lib/scope/index.js:125:12)
    at NodePath._call (/home/test/antd-admin/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/home/test/antd-admin/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/home/test/antd-admin/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/home/test/antd-admin/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/home/test/antd-admin/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/home/test/antd-admin/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/home/test/antd-admin/node_modules/@babel/traverse/lib/index.js:94:17)
    at traverse (/home/test/antd-admin/node_modules/@babel/traverse/lib/index.js:76:12)
    at NodePath.traverse (/home/test/antd-admin/node_modules/@babel/traverse/lib/path/index.js:161:24)
    at Scope.crawl (/home/test/antd-admin/node_modules/@babel/traverse/lib/scope/index.js:684:10)
    at PluginPass.Program (/home/test/antd-admin/node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js:361:29)

 @ ./src/pages/.umi-production/router.js 26:13-28:31
 @ ./src/pages/.umi-production/umi.js
 @ multi ./src/pages/.umi-production/umi.js

 error  in ./src/pages/404.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /home/test/antd-admin/src/pages/404.js: Duplicate declaration "React"
> 1 | import React from 'react'

**Comment by superlbr** [comment]
wait a second, I'll fix it.
while, remove all react import and add is a good choice

**Comment by superlbr** [comment]
follow in https://github.com/umijs/umi/issues/1588

**Comment by kaobez** [comment]
yarn build也不行。去掉import react可以build成功，但用不了。
保留import react只能start，不能build。主要是初次接触react这套，不知道该去哪些。。。
几年没碰前端，本来准备熟悉的jquery发现已经消失了，但是react这里很多框架堆一起，暂时还没搞清头绪，大佬能给个build成功的方式么。

**Comment by superlbr** [comment]
fallback to umi@2.2.8 is fine

**Comment by wangjiafenghw** [comment]
> yarn build也不行。去掉import react可以build成功，但用不了。
> 保留import react只能start，不能build。主要是初次接触react这套，不知道该去哪些。。。
> 几年没碰前端，本来准备熟悉的jquery发现已经消失了，但是react这里很多框架堆一起，暂时还没搞清头绪，大佬能给个build成功的方式么。

@sorrycc 哥呀，来帮看看吧，我的也是这个问题

**Comment by kaobez** [comment]
@wangjiafenghw fallback to umi@2.2.8 is fine
